sudo: required

language: python

services:
  - docker

install:
  - docker build -t lowerquality/gentle .

#script:
#  - docker run --rm lowerquality/gentle sh -c "cd /gentle && python3 setup.py test"
